name: Deploy Node.js Azure Function App

on:
  push:
    branches:
      - main

env:
  AZURE_FUNCTIONAPP_NAME: 'fn-order-vugiakhoi'
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.'
  NODE_VERSION: '18.x'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v3

    - name: Setup Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}

    - name: 'Install dependencies'
      shell: bash
      run: |
        pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
        npm install
        popd

    - name: 'Zip code for deployment'
      run: |
        zip -r release.zip . -x "*.git*" "node_modules/azure-functions-core-tools/*"

    - name: 'Log in to Azure'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: 'Deploy to Azure Function App (Flex)'
      run: |
        az functionapp deployment source config-zip \
          --resource-group rg-serverless-order \
          --name ${{ env.AZURE_FUNCTIONAPP_NAME }} \
          --src release.zip